// ROOT STORE @/store/index.js
export const CHANGE_COOKIE = 'CHANGE_COOKIE'
export const CHANGE_COOKIE_BOOLEAN = 'CHANGE_COOKIE_BOOLEAN'
export const ERASE_COOKIE = 'ERASE_COOKIE'

// TABLEAUX @/store/modules/StoreTableaus.js
export const SET_APIs_LOADED = 'SET_APIs_LOADED'
export const SET_APIs = 'SET_APIs'
export const SET_GAPI_CLIENT_LOADED = 'SET_GAPI_CLIENT_LOADED'
export const SET_GAPI_CLIENT = 'SET_GAPI_CLIENT'

// AUTH @/store/modules/StoreAuth.js
export const LOAD_HEADERS = 'LOAD_HEADERS'
export const CHANGE_HEADERS_LOADED_STATE = 'CHANGE_HEADERS_LOADED_STATE'
export const CHANGE_HEADERS_ERRORED_STATE = 'CHANGE_HEADERS_ERRORED_STATE'
export const SET_USER = 'SET_USER'
export const SET_AUTH_STATE = 'SET_AUTH_STATE'
export const RESET_USER = 'RESET_USER'
export const CHANGE_USER_LOADED_STATE = 'CHANGE_USER_LOADED_STATE'
export const CHANGE_USER_ERRORED_STATE = 'CHANGE_USER_ERRORED_STATE'

